experiment: 'genhead-ffhq512'
outdir: './training-runs-genhead'
data: None
gpus: 4
batch: 32
g_module: 'training.generator.triplane.PartTriPlaneGeneratorDeform'
d_module: 'training.discriminator.dual_discriminator.DualDiscriminatorDeform'
triplane_resolution: 256
triplane_channels: 192
g_has_superresolution: True
g_has_background: True
g_flame_condition: True
g_random_combine: False
g_dynamic_texture: False
g_flame_full: True
d_has_superresolution: True
d_has_uv: True
d_has_seg: True
patch_scale: 1.0